import { readFile, writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import MarkdownIt from 'markdown-it';
import matter from 'gray-matter';

const base = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = file => readFile(path.join(base, file), 'utf8');
const profile = JSON.parse(await read('content/profile.json'));
const projects = JSON.parse(await read('content/projects.json'));
const template = await read('templates/page.html');
const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const arrow = '<span aria-hidden="true">↗</span>';
const md = new MarkdownIt({ html: false, linkify: true, typographer: true });
// Tables remain usable on narrow screens, including without JavaScript.
md.renderer.rules.table_open = () => '<div class="table-scroll" tabindex="0" role="region" aria-label="Data table"><table>\n';
md.renderer.rules.table_close = () => '</table></div>\n';
const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const usedSlugs = new Set();
const dateLabel = date => new Date(`${date}T12:00:00Z`).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric', timeZone: 'UTC' });
const tagList = tags => tags.map(tag => `<span class="tag">${escape(tag)}</span>`).join('');
const label = (n, text) => `<p class="eyebrow"><span>${n}</span> ${text}</p>`;
const heading = (n, title, description, link = '') => `<div class="section-heading"><h2>${title}</h2>${link}</div>`;
const posts = [];
for (const file of (await readdir(path.join(base, 'content/posts'))).filter(f => f.endsWith('.md'))) {
  const { data, content } = matter(await read(`content/posts/${file}`));
  if (data.draft) continue;
  if (!data.title || !data.description || !slugPattern.test(data.slug) || usedSlugs.has(data.slug)) throw new Error(`Invalid or duplicate post metadata: ${file}`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(data.date) || Number.isNaN(Date.parse(data.date)) || new Date(data.date).toISOString().slice(0, 10) !== data.date) throw new Error(`Use a quoted YYYY-MM-DD date in ${file}`);
  if (!Array.isArray(data.tags) || !data.cover || !data.coverAlt) throw new Error(`Missing tags or cover metadata: ${file}`);
  usedSlugs.add(data.slug);
  const tokens = md.parse(content, {});
  const toc = [];
  const headingIds = new Map();
  for (let i = 0; i < tokens.length; i++) {
    if (tokens[i].type !== 'heading_open') continue;
    const text = tokens[i + 1].content;
    const stem = text.toLowerCase().replace(/[^\p{L}\p{N}]+/gu, '-').replace(/^-|-$/g, '') || 'section';
    const count = (headingIds.get(stem) || 0) + 1;
    headingIds.set(stem, count);
    const id = count === 1 ? stem : `${stem}-${count}`;
    tokens[i].attrSet('id', id);
    if (tokens[i].tag === 'h2') toc.push({ id, text });
  }
  const words = content.split(/\s+/).length;
  posts.push({ ...data, content, html: md.renderer.render(tokens, md.options, {}), toc, minutes: Math.max(1, Math.ceil(words / 200)) });
}
posts.sort((a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug));
const year = new Date().getUTCFullYear();
async function page(file, title, description, content, { root = '', blog = false, lang = 'en', article = false } = {}) {
  const values = { name: escape(profile.name), chineseName: escape(profile.chineseName), github: escape(profile.github), title: escape(title), description: escape(description), content, root, year, lang: escape(lang), blogCurrent: blog ? 'aria-current="page"' : '', ogType: article ? 'article' : 'website' };
  const output = '<!-- Generated by npm run build. Edit content/ and templates/ instead. -->\n' + template.replace(/{{(\w+)}}/g, (_, key) => values[key] ?? '');
  await mkdir(path.dirname(path.join(base, file)), { recursive: true });
  await writeFile(path.join(base, file), output);
}
function projectCard(project, index, root = '') {
  return `<a class="project-card glass" href="${root}projects/${escape(project.slug)}/index.html"><div class="project-title"><h3>${escape(project.name)}</h3>${arrow}</div><p>${escape(project.subtitle)}</p></a>`;
}
function postCard(post, root = '') {
  return `<a class="post-card glass" href="${root}blog/${escape(post.slug)}/index.html"><div class="post-image"><img src="${root}${escape(post.cover)}" alt="${escape(post.coverAlt)}" width="1200" height="800" loading="lazy"></div><div class="post-card-body"><p class="post-meta"><time datetime="${post.date}">${dateLabel(post.date)}</time></p><h3>${escape(post.title)}</h3><p>${escape(post.description)}</p></div></a>`;
}

const home = `
<section class="hero container" id="home">
  <div class="hero-copy"><p class="hero-role">${escape(profile.role)} · USTC</p><h1>${escape(profile.name)}<span class="chinese-name">${escape(profile.chineseName)}</span></h1><p class="hero-statement">${escape(profile.intro).replace("reason, act, and learn.", "<br>reason, act, <em>and learn.</em>")}</p><div class="hero-actions"><a class="button button-dark" href="#projects">Explore my work ${arrow}</a><a class="text-link" href="mailto:${escape(profile.email)}">Get in touch ${arrow}</a></div><p class="hero-affiliation">${escape(profile.affiliation)} · ${escape(profile.location)}</p></div>
  <div class="hero-visual"><img class="hero-photo" src="assets/images/mountains.jpg" alt="Mountain peaks surrounded by clouds" width="1200" height="800" fetchpriority="high"><div class="visual-note glass-light"><p>Learning through experience.</p></div><span class="photo-credit">Landscape · Unsplash</span></div>
</section>
<section class="section container about-section" id="about">${heading('01', 'About me', '')}<div class="about-text">${profile.about.map(p => `<p>${p}</p>`).join('')}</div></section>
<section class="section container" id="research">${heading('02', 'Research', '')}<div class="research-grid">${profile.research.map(r => `<article class="research-card"><h3>${escape(r.title)}</h3><p>${escape(r.description)}</p></article>`).join('')}</div></section>
<section class="section container" id="projects">${heading('03', 'Selected projects', '', '<a class="text-link" href="projects/index.html">All projects '+arrow+'</a>')}<div class="projects-grid">${projects.map((p, i) => projectCard(p, i)).join('')}</div></section>
<section class="section container" id="blog">${heading('04', 'Writing', '', '<a class="text-link" href="blog/index.html">All writing '+arrow+'</a>')}<div class="home-blog">${posts.slice(0, 1).map(p => postCard(p)).join('')}<div class="notebook-note"><h3>Notes along the way.</h3><p>Research reflections, things I’m learning, and the occasional detour.</p></div></div></section>
<section class="section container" id="education">${heading('05', 'Education', '')}<div class="education-grid"><article class="education-card glass"><p class="education-date">${escape(profile.education.date)}</p><h3>${escape(profile.education.school)}</h3><p class="degree">${escape(profile.education.degree)}</p><p>${escape(profile.education.detail)}</p><div class="advisor">Research advisor <strong>${escape(profile.education.advisor)}</strong></div></article><div class="education-aside"><div><h3>Honors & awards</h3><ul class="plain-list">${profile.honors.map(h => `<li>${escape(h)}</li>`).join('')}</ul></div><div><h3>Languages</h3><ul class="plain-list">${profile.languages.map(l => `<li>${escape(l)}</li>`).join('')}</ul></div></div></div></section>
<section class="contact-section container" id="contact"><div class="contact-panel glass"><h2>Let’s <em>connect.</em></h2><div class="contact-actions"><a class="text-link" href="mailto:${escape(profile.email)}">${escape(profile.email)} ${arrow}</a><a class="text-link" href="${escape(profile.github)}">GitHub ${arrow}</a></div></div></section>`;
await page('index.html', `${profile.name} — Research & Notes`, profile.description, home);

await page('projects/index.html', `Projects — ${profile.name}`, 'Selected research and engineering projects by Yuqiao Chen.', `<div class="container archive"><a class="back-link" href="../index.html">← Back to home</a><div class="archive-heading"><h1>Projects</h1><p>Selected research and engineering work.</p></div><div class="projects-grid">${projects.map((p, i) => projectCard(p, i, '../')).join('')}</div></div>`, { root: '../' });
const projectSlugs = new Set();
for (const [i, project] of projects.entries()) {
  if (!slugPattern.test(project.slug) || projectSlugs.has(project.slug)) throw new Error(`Invalid project slug: ${project.slug}`);
  projectSlugs.add(project.slug);
  if (project.url && !/^https:\/\//.test(project.url)) throw new Error(`Project URLs must use HTTPS: ${project.slug}`);
  const next = projects[(i + 1) % projects.length];
  const body = `<div class="container detail-page"><a class="back-link" href="../index.html">← All projects</a><header class="detail-heading"><p class="project-date">${escape(project.date)}</p><h1>${escape(project.name)}</h1><p class="detail-subtitle">${escape(project.title)}</p></header><div class="project-detail-layout"><article class="prose project-prose glass"><h2>Overview</h2><p>${escape(project.subtitle)}.</p><h2>Work & contributions</h2><ul>${project.details.map(d => `<li>${d}</li>`).join('')}</ul>${project.url ? `<a class="button button-dark" href="${escape(project.url)}">Visit project ${arrow}</a>` : ''}</article><aside class="project-sidebar"><div class="glass sidebar-panel"><dl><dt>Area</dt><dd>${escape(project.tags.join(' · '))}</dd><dt>Timeline</dt><dd>${escape(project.date)}</dd></dl><a class="text-link" href="mailto:${escape(profile.email)}">Discuss this work ${arrow}</a></div></aside></div><a class="next-project" href="../${escape(next.slug)}/index.html"><span>Next project</span><strong>${escape(next.name)} ${arrow}</strong></a></div>`;
  await page(`projects/${project.slug}/index.html`, `${project.name} — ${profile.name}`, project.subtitle, body, { root: '../../', article: true });
}

await page('blog/index.html', `Blog — ${profile.name}`, 'Research reflections, learning notes, and everyday discoveries.', `<div class="container archive"><a class="back-link" href="../index.html">← Back to home</a><div class="archive-heading"><h1>Writing</h1><p>Research notes and everyday discoveries.</p></div><div class="blog-grid">${posts.length ? posts.map(p => postCard(p, '../')).join('') : '<p>New notes are on the way.</p>'}</div></div>`, { root: '../', blog: true });
for (const post of posts) {
  const body = `<div class="container detail-page article-page"><a class="back-link" href="../index.html">← All writing</a><header class="detail-heading"><div class="tags">${tagList(post.tags)}</div><h1>${escape(post.title)}</h1><p class="detail-subtitle">${escape(post.description)}</p><div class="article-meta"><span class="author-avatar" aria-hidden="true">YC</span><div><strong>${escape(profile.name)}</strong><p><time datetime="${post.date}">${dateLabel(post.date)}</time> · ${post.minutes} min read</p></div></div></header><div class="article-layout"><article class="prose blog-prose">${post.html}<div class="article-end"><a class="text-link" href="../index.html">More from the notebook ${arrow}</a></div></article><aside class="toc"><nav aria-label="Table of contents"><p class="eyebrow">ON THIS PAGE</p>${post.toc.map(item => `<a href="#${escape(item.id)}">${escape(item.text)}</a>`).join('')}</nav></aside></div></div>`;
  await page(`blog/${post.slug}/index.html`, `${post.title} — ${profile.name}`, post.description, body, { root: '../../', blog: true, lang: post.lang || 'en', article: true });
}
const files = ['index.html', 'projects/index.html', 'blog/index.html', ...projects.map(p => `projects/${p.slug}/index.html`), ...posts.map(p => `blog/${p.slug}/index.html`)];
let previous = [];
try { previous = JSON.parse(await read('content/generated-pages.json')); } catch (error) { if (error.code !== 'ENOENT') throw error; }
// Remove only pages previously owned by the generator (e.g. unpublished drafts).
for (const file of previous.filter(f => !files.includes(f))) {
  if (!/^(blog|projects)\/[a-z0-9-]+\/index\.html$/.test(file)) throw new Error(`Unsafe generated page path: ${file}`);
  try { await unlink(path.join(base, file)); } catch (error) { if (error.code !== 'ENOENT') throw error; }
}
await writeFile(path.join(base, 'content/generated-pages.json'), JSON.stringify(files, null, 2) + '\n');
console.log(`Built ${files.length} pages: ${projects.length} projects, ${posts.length} published posts.`);
